version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 3535:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
