version: '3.7'

services:
    collaction-api:
        container_name: collaction-api
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./src:/home/node/app/src
        expose:
            - ${PORT}
        ports:
            - ${PORT}:${PORT}
        command: npm run start:dev
