on:
    pull_request:
        branches:
            - master
            - development
            - 'project/**'

jobs:
    checks:
        name: Run Code Checks
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm ci --ignore-scripts --quiet

            - name: Run Linters
              run: npm run lint

            - name: Run Tests
              run: npm run test
