name: Deploy to Azure

on:
    push:
        branches: [development, master, azure]

env:
    #CURRENT_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
    CURRENT_ENV: development

jobs:
    build:
        environment: development
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Azure CLI login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZ_CREDENTIALS }}

            - name: Azure Container Registry login
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.AZ_REGISTRY_URL }}
                  username: ${{ secrets.AZ_REGISTRY_USERNAME }}
                  password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

            - name: Build, tag and push image to Azure Container Registry
              env:
                  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                  ENV_FILE: ${{ secrets.ENV }}
                  ECR_REGISTRY: ${{ secrets.AZ_REGISTRY_URL }}
                  ECR_REPOSITORY: collaction-api-${{ env.CURRENT_ENV }}
              run: |
                  echo $SERVICE_ACCOUNT_KEY | base64 --decode > serviceAccountKey.json
                  echo $ENV_FILE | base64 --decode > .env
                  docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

            - name: Deploy to Azure App Service
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'collaction-api-${{ env.CURRENT_ENV }}'
                publish-profile: ${{ secrets.AZ_PUBLISH_PROFILE }}
                images: '${{ secrets.AZ_REGISTRY_URL }}/collaction-api-${{ env.CURRENT_ENV }}:${{ github.sha }}'

