name: Deploy to Azure

on:
    push:
        branches: [development, master, azure]

env:
    #CURRENT_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
    CURRENT_ENV: production

jobs:
    build:
        environment: production
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZ_CREDENTIALS }}

            - name: Login to Azure Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.AZ_REGISTRY_URL }}
                  username: ${{ secrets.AZ_REGISTRY_USERNAME }}
                  password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

            - name: Build, tag, and push image to Azure Container Instances
              env:
                  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                  ENV_FILE: ${{ secrets.ENV }}
                  ECR_REGISTRY: ${{ secrets.AZ_REGISTRY_URL }}
                  ECR_REPOSITORY: collaction-api-${{ env.CURRENT_ENV }}
              run: |
                  echo $SERVICE_ACCOUNT_KEY | base64 --decode > serviceAccountKey.json
                  echo $ENV_FILE | base64 --decode > .env
                  docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

            - name: Deploy to Azure Container Instances
              uses: azure/aci-deploy@v1
              env:
                  ECR_REPOSITORY: collaction-api-${{ env.CURRENT_ENV }}
              with:
                  resource-group: ${{ secrets.AZ_RESOURCE_GROUP }}
                  dns-name-label: ${{ env.CURRENT_ENV }}-api
                  image: ${{ secrets.AZ_REGISTRY_URL }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
                  registry-login-server: ${{ secrets.AZ_REGISTRY_URL }}
                  registry-username: ${{ secrets.AZ_REGISTRY_USERNAME }}
                  registry-password: ${{ secrets.AZ_REGISTRY_PASSWORD }}
                  cpu: 1
                  memory: 2.0
                  name: ${{ env.ECR_REPOSITORY }}
                  location: 'west europe'
                  ports: '80 443 3000'
